# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  bash <(curl -s -L https://detect.synopsys.com/detect8.sh) --blackduck.url=https://us1a-imp-hub10.nprd.sig.synopsys.com --blackduck.api.token=OTgwMmE0NDQtODI1OC00MjlmLWI4NzgtNTQxYTRhYTkyMDU0Ojc0OGM2ODU2LWJlMTMtNGU1Ni1iYjQ1LWNhODdkYzRkMWU1Mg== --blackduck.trust.cert=true
  powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect8.ps1?$(Get-Random) | iex; detect“ --blackduck.url=https://us1a-imp-hub10.nprd.sig.synopsys.com --blackduck.api.token=OTgwMmE0NDQtODI1OC00MjlmLWI4NzgtNTQxYTRhYTkyMDU0Ojc0OGM2ODU2LWJlMTMtNGU1Ni1iYjQ1LWNhODdkYzRkMWU1Mg== --blackduck.trust.cert=true
